import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ChevronDown, Menu, X } from "lucide-react";
import UserHeader from "@/components/UserHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="bg-gray-50 min-h-screen">
          {/* <div className="flex h-screen overflow-auto"> */}
          {/* <!--- Side navbar ---> */}
          {/* <div className="flex-1"> */}
          {/* <!--- Header with search bar  ---> */}
          <UserHeader />
          {/* <!--- Main content  ---> */}
          {children}
          {/* </div> */}
          {/* </div> */}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
