// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import AdminAsidebar from "@/components/admin/AdminAsidebar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <div className="min-h-screen bg-gray-50">
//           <div className="flex h-screen overflow-hidden">
//             {/* Sidebar */}
//             <AdminAsidebar />
//             {/* Main Content */}
//             {children}
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AdminAsidebar from "@/components/admin/AdminAsidebar";
import Adminheader from "@/components/admin/Adminheader";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="min-h-screen bg-gray-50">
          <div className="flex h-screen overflow-hidden">
            {/* <!--- Side navbar ---> */}
            <AdminAsidebar />
            <div className="flex-1">
              {/* <!--- Header with search bar  ---> */}
              <Adminheader />
              {/* <!--- Main content  ---> */}
              {children}
            </div>
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
